/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SupplyChainTrackingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "adjustThresholds"
      | "allowProductComplianceDecryptionFor"
      | "allowThresholdDecryptionFor"
      | "calculateRiskScore"
      | "checkCompliance"
      | "confidentialProtocolId"
      | "getProductCount"
      | "getProductInfo"
      | "getThresholdHandles"
      | "owner"
      | "productCounter"
      | "products"
      | "registerProduct"
      | "thresholdsInitialized"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ComplianceChecked"
      | "ProductRegistered"
      | "RiskCalculated"
      | "ThresholdsAdjusted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "adjustThresholds",
    values: [
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "allowProductComplianceDecryptionFor",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allowThresholdDecryptionFor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateRiskScore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkCompliance",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProductCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProductInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getThresholdHandles",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "productCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "products",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerProduct",
    values: [BytesLike, BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "thresholdsInitialized",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "adjustThresholds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allowProductComplianceDecryptionFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allowThresholdDecryptionFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateRiskScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkCompliance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProductCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProductInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getThresholdHandles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "productCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "products", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerProduct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "thresholdsInitialized",
    data: BytesLike
  ): Result;
}

export namespace ComplianceCheckedEvent {
  export type InputTuple = [productId: BigNumberish];
  export type OutputTuple = [productId: bigint];
  export interface OutputObject {
    productId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProductRegisteredEvent {
  export type InputTuple = [productId: BigNumberish, owner: AddressLike];
  export type OutputTuple = [productId: bigint, owner: string];
  export interface OutputObject {
    productId: bigint;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RiskCalculatedEvent {
  export type InputTuple = [productId: BigNumberish];
  export type OutputTuple = [productId: bigint];
  export interface OutputObject {
    productId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ThresholdsAdjustedEvent {
  export type InputTuple = [actor: AddressLike];
  export type OutputTuple = [actor: string];
  export interface OutputObject {
    actor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SupplyChainTracking extends BaseContract {
  connect(runner?: ContractRunner | null): SupplyChainTracking;
  waitForDeployment(): Promise<this>;

  interface: SupplyChainTrackingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  adjustThresholds: TypedContractMethod<
    [
      maxCostThreshold: BytesLike,
      minSupplierScoreThreshold: BytesLike,
      maxRiskParamThreshold: BytesLike,
      weight1: BytesLike,
      weight2: BytesLike,
      weight3: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  allowProductComplianceDecryptionFor: TypedContractMethod<
    [productId: BigNumberish, user: AddressLike],
    [void],
    "nonpayable"
  >;

  allowThresholdDecryptionFor: TypedContractMethod<
    [user: AddressLike],
    [void],
    "nonpayable"
  >;

  calculateRiskScore: TypedContractMethod<
    [productId: BigNumberish],
    [void],
    "nonpayable"
  >;

  checkCompliance: TypedContractMethod<
    [productId: BigNumberish],
    [void],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getProductCount: TypedContractMethod<[], [bigint], "view">;

  getProductInfo: TypedContractMethod<
    [productId: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        bigint
      ] & {
        batchNumber: string;
        cost: string;
        supplierScore: string;
        riskParam: string;
        isCompliant: string;
        riskFlag: string;
        riskScore: string;
        productOwner: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getThresholdHandles: TypedContractMethod<
    [],
    [
      [string, string, string, string, string, string] & {
        maxCostThreshold: string;
        minSupplierScoreThreshold: string;
        maxRiskParamThreshold: string;
        weight1: string;
        weight2: string;
        weight3: string;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  productCounter: TypedContractMethod<[], [bigint], "view">;

  products: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        bigint
      ] & {
        batchNumber: string;
        cost: string;
        supplierScore: string;
        riskParam: string;
        isCompliant: string;
        riskFlag: string;
        riskScore: string;
        owner: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  registerProduct: TypedContractMethod<
    [
      batchNumber: BytesLike,
      cost: BytesLike,
      supplierScore: BytesLike,
      riskParam: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  thresholdsInitialized: TypedContractMethod<[], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "adjustThresholds"
  ): TypedContractMethod<
    [
      maxCostThreshold: BytesLike,
      minSupplierScoreThreshold: BytesLike,
      maxRiskParamThreshold: BytesLike,
      weight1: BytesLike,
      weight2: BytesLike,
      weight3: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "allowProductComplianceDecryptionFor"
  ): TypedContractMethod<
    [productId: BigNumberish, user: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "allowThresholdDecryptionFor"
  ): TypedContractMethod<[user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "calculateRiskScore"
  ): TypedContractMethod<[productId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "checkCompliance"
  ): TypedContractMethod<[productId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getProductCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getProductInfo"
  ): TypedContractMethod<
    [productId: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        bigint
      ] & {
        batchNumber: string;
        cost: string;
        supplierScore: string;
        riskParam: string;
        isCompliant: string;
        riskFlag: string;
        riskScore: string;
        productOwner: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getThresholdHandles"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, string, string, string] & {
        maxCostThreshold: string;
        minSupplierScoreThreshold: string;
        maxRiskParamThreshold: string;
        weight1: string;
        weight2: string;
        weight3: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "productCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "products"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        bigint
      ] & {
        batchNumber: string;
        cost: string;
        supplierScore: string;
        riskParam: string;
        isCompliant: string;
        riskFlag: string;
        riskScore: string;
        owner: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerProduct"
  ): TypedContractMethod<
    [
      batchNumber: BytesLike,
      cost: BytesLike,
      supplierScore: BytesLike,
      riskParam: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "thresholdsInitialized"
  ): TypedContractMethod<[], [boolean], "view">;

  getEvent(
    key: "ComplianceChecked"
  ): TypedContractEvent<
    ComplianceCheckedEvent.InputTuple,
    ComplianceCheckedEvent.OutputTuple,
    ComplianceCheckedEvent.OutputObject
  >;
  getEvent(
    key: "ProductRegistered"
  ): TypedContractEvent<
    ProductRegisteredEvent.InputTuple,
    ProductRegisteredEvent.OutputTuple,
    ProductRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "RiskCalculated"
  ): TypedContractEvent<
    RiskCalculatedEvent.InputTuple,
    RiskCalculatedEvent.OutputTuple,
    RiskCalculatedEvent.OutputObject
  >;
  getEvent(
    key: "ThresholdsAdjusted"
  ): TypedContractEvent<
    ThresholdsAdjustedEvent.InputTuple,
    ThresholdsAdjustedEvent.OutputTuple,
    ThresholdsAdjustedEvent.OutputObject
  >;

  filters: {
    "ComplianceChecked(uint256)": TypedContractEvent<
      ComplianceCheckedEvent.InputTuple,
      ComplianceCheckedEvent.OutputTuple,
      ComplianceCheckedEvent.OutputObject
    >;
    ComplianceChecked: TypedContractEvent<
      ComplianceCheckedEvent.InputTuple,
      ComplianceCheckedEvent.OutputTuple,
      ComplianceCheckedEvent.OutputObject
    >;

    "ProductRegistered(uint256,address)": TypedContractEvent<
      ProductRegisteredEvent.InputTuple,
      ProductRegisteredEvent.OutputTuple,
      ProductRegisteredEvent.OutputObject
    >;
    ProductRegistered: TypedContractEvent<
      ProductRegisteredEvent.InputTuple,
      ProductRegisteredEvent.OutputTuple,
      ProductRegisteredEvent.OutputObject
    >;

    "RiskCalculated(uint256)": TypedContractEvent<
      RiskCalculatedEvent.InputTuple,
      RiskCalculatedEvent.OutputTuple,
      RiskCalculatedEvent.OutputObject
    >;
    RiskCalculated: TypedContractEvent<
      RiskCalculatedEvent.InputTuple,
      RiskCalculatedEvent.OutputTuple,
      RiskCalculatedEvent.OutputObject
    >;

    "ThresholdsAdjusted(address)": TypedContractEvent<
      ThresholdsAdjustedEvent.InputTuple,
      ThresholdsAdjustedEvent.OutputTuple,
      ThresholdsAdjustedEvent.OutputObject
    >;
    ThresholdsAdjusted: TypedContractEvent<
      ThresholdsAdjustedEvent.InputTuple,
      ThresholdsAdjustedEvent.OutputTuple,
      ThresholdsAdjustedEvent.OutputObject
    >;
  };
}
